### ISSUE TITLE
watchdog flooded with

### ISSUE THREAD

**Issue by KarinG** [eileenmcnaughton/civicrm_entity#261]
```
Notice: Undefined offset: 2 in CRM_Contact_BAO_Query->convertToPseudoNames() (line 6047 of /var/www/drupal/vendor/civicrm/civicrm-core/CRM/Contact/BAO/Query.php)

#0 /var/www/drupal/web/core/includes/bootstrap.inc(600): _drupal_error_handler_real(8, 'Undefined offse...', '/var/www/drupal...', 6047, Array)
#1 /var/www/drupal/vendor/civicrm/civicrm-core/CRM/Contact/BAO/Query.php(6047): _drupal_error_handler(8, 'Undefined offse...', '/var/www/drupal...', 6047, Array)
#2 /var/www/drupal/vendor/civicrm/civicrm-core/api/v3/Participant.php(152): CRM_Contact_BAO_Query->convertToPseudoNames(Object(CRM_Core_DAO), false, true)
#3 /var/www/drupal/vendor/civicrm/civicrm-core/Civi/API/Provider/MagicFunctionProvider.php(89): civicrm_api3_participant_get(Array)
#4 /var/www/drupal/vendor/civicrm/civicrm-core/Civi/API/Kernel.php(150): Civi\API\Provider\MagicFunctionProvider->invoke(Array)
#5 /var/www/drupal/vendor/civicrm/civicrm-core/Civi/API/Kernel.php(81): Civi\API\Kernel->runRequest(Array)
#6 /var/www/drupal/vendor/civicrm/civicrm-core/api/api.php(22): Civi\API\Kernel->runSafe('Participant', 'get', Array)
#7 /var/www/drupal/vendor/civicrm/civicrm-core/api/v3/Generic.php(281): civicrm_api('Participant', 'get', Array)
#8 /var/www/drupal/vendor/civicrm/civicrm-core/Civi/API/Provider/MagicFunctionProvider.php(85): civicrm_api3_generic_getcount(Array)
#9 /var/www/drupal/vendor/civicrm/civicrm-core/Civi/API/Kernel.php(150): Civi\API\Provider\MagicFunctionProvider->invoke(Array)
#10 /var/www/drupal/vendor/civicrm/civicrm-core/Civi/API/Kernel.php(81): Civi\API\Kernel->runRequest(Array)
#11 /var/www/drupal/vendor/civicrm/civicrm-core/api/api.php(131): Civi\API\Kernel->runSafe('participant', 'getcount', Array)
#12 /var/www/drupal/web/sites/default/modules/civicrm_entity/src/CiviCrmApi.php(90): civicrm_api3('participant', 'getcount', Array)
#13 /var/www/drupal/web/sites/default/modules/civicrm_entity/src/CiviEntityStorage.php(285): Drupal\civicrm_entity\CiviCrmApi->getCount('participant')
```

6 pages:
![image](https://user-images.githubusercontent.com/5340555/102549425-4eab4600-4079-11eb-879b-769d5279e802.png)

**Comment by KarinG** [comment]
Will try look into this this afternoon when we have some dev time.

**Comment by jackrabbithanna** [comment]
Do you know what kind of page or when these messages are showing up? I hadn't seen this one yet, although with the exception of our Drupal 9 testbed, we're still using Civi 5.27

Looking at the backtrace, it's doing a 'getcount' API call with participants. 

No other CE or drupal functions being called. Feels like potentially a CiviCRM Core bug.

**Comment by KarinG** [comment]
Just about any page! This is a Civi 5.28 (latest non-extended security release).

This client got a little excited and has enabled just about every checkbox -> 
![image](https://user-images.githubusercontent.com/5340555/102551470-c6c73b00-407c-11eb-867a-d4606c31967e.png)

I don't see this on another Civi 5.28 that does not have any entities exposed.

**Comment by KarinG** [comment]
So I think they mistakenly checked all these boxes -> can these be safely unchecked?

**Comment by KarinG** [comment]
I think the answer is 'yes' - but I still remember when I destroyed my own site trying to uninstall :-)

**Comment by jackrabbithanna** [comment]
Yeah you can uncheck there no problem. 

Hard to see how this is a CE bug ..

**Comment by KarinG** [comment]
Oh I think you're right - we will get to the bottom of this.
